on:
  pull_request:
    types:
      - ready_for_review

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'recipes')
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: linux-64, os: ubuntu-20.04 }
          - { target: win-64, os: windows-latest }
          # force older macos-13 to get x86_64 runners
          - { target: osx-64, os: macos-13 }
          - { target: osx-arm64, os: macos-14 }
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    outputs:
      uploaded-artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: â¬‡ï¸ Git Checkout
        uses: actions/checkout@v4

      - name: âš™ï¸ Install pixi env
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.0

      - name: âš™ï¸ Add .pixi/envs/default/bin to the $PATH
        shell: bash
        run: |
          echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

      - name: ğŸ“¦ Build Changed Recipes
        shell: bash
        run: |
          rattler-build build --recipe-dir ./forge \
            --skip-existing=all --target-platform=${{ matrix.target }} \
            -c conda-forge -c https://prefix.dev/brads-forge

      - name: â¬†ï¸ Upload Conda Packages
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{ matrix.target }}
          path: output/${{ matrix.target }}/*.conda
