on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:
      - name: âš™ï¸ Lookup PR RunId
        id: pr-lookup
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          echo "run-id=$(gh api /repos/${{ github.repository }}/actions/workflows/build.yaml/runs
          --method GET -f head_sha=${{ github.event.pull_request.head.sha }} --jq '.workflow_runs[0].id')"
          >> $GITHUB_OUTPUT

      - name: â¬‡ï¸ Download Built Conda Packages
        uses: actions/download-artifact@v4
        with:
          path: ./output
          run-id: ${{ steps.pr-lookup.outputs.run-id }}
          github-token: ${{ github.token }}

      - name: ğŸ‰ Publish to prefix.dev
        run: |
          for file in output/**/*.conda; do
            rattler-build upload prefix -c brads-forge "$file"
          done
